#!/usr/bin/env bash
#Install nginx

sudo apt-get update

sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i 's/\blisten 80 default_server\b/listen 80 default_server;/g' /etc/nginx/sites-available/default
