#!/usr/bin/env bash
#Bash script containing commands to automatically configure a Ubuntu machine to respect above requirements

sudo apt-get -y update

sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html';

sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.github.com/ZiadHamdyy/ permanent;' /etc/nginx/sites-available/default;

sudo service nginx restart;
