#!/usr/bin/env bash
#Install nginx

sudo apt-get update

sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html';

sudo sed -i 's/\blisten 80 default_server\b/listen 80 default_server;/g' /etc/nginx/sites-available/default

sudo service nginx start;
