#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on all active IPs on port 8080

sudo sed -i 's/user\s*[^;]*;/user nginx;/' /etc/nginx/nginx.conf

chmod 444 /etc/nginx/nginx.conf
pkill apache2

sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default

sudo -u nginx service nginx restart
