#!/usr/bin/env bash
#make your fix short and sweet

sed -i 's/user\s*[^;]*;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*[^;]*;/listen 8080;/g' /etc/nginx/sites-available/default
nginx -t
service nginx restart

